// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20240105082643_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Models.BasketModel", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("ProductCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductFeatures")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("float");

                    b.Property<int>("ProductStar")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("BasketTable");

                    b.HasData(
                        new
                        {
                            ProductId = 22,
                            ProductCategory = "Spor",
                            ProductFeatures = "Vites:24 Vites ,  Bisiklet Tipi:Dağ Bisikleti , Kadro Malzemesi:Alüminyum Ağırlık 14,6 kg ,  Fren Tipi:Hidrolik Disk Fren , Jant:29 inç, Kadro Boyu:18 inç - 46 cm ,Ön Amortisör :Kilitli Amortisör",
                            ProductImgUrl = "https://productimages.hepsiburada.net/s/55/550/11212783550514.jpg/format:webp",
                            ProductName = "Dağ Bisikleti",
                            ProductPrice = 18000.0,
                            ProductStar = 10
                        });
                });

            modelBuilder.Entity("API.Models.ProductModel", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("ProductCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductFeatures")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("float");

                    b.Property<int>("ProductStar")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("ProductTable");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ProductCategory = "Teknoloji",
                            ProductFeatures = "Intel Core i7 12650H 16GB 512GB SSD RTX3050 Freedos 15.6\" FHD 144Hz ",
                            ProductImgUrl = "https://productimages.hepsiburada.net/s/448/550/110000481950429.jpg/format:webp",
                            ProductName = "MSI THIN GF63 12UC-666XTR",
                            ProductPrice = 30999.0,
                            ProductStar = 9
                        },
                        new
                        {
                            ProductId = 2,
                            ProductCategory = "Teknoloji",
                            ProductFeatures = "Bluetooth Versiyon5.0, Çift Telefon Desteği Yok, Suya & Tere DayanıklıHayırAktif Gürültü Önleme (ANC)Yok, Kullanım TipiKulakiçi ",
                            ProductImgUrl = "https://productimages.hepsiburada.net/s/430/222-222/110000462400807.jpg/format:webp",
                            ProductName = "Apple AirPods 2. Nesil Kulaklık",
                            ProductPrice = 3199.0,
                            ProductStar = 9
                        },
                        new
                        {
                            ProductId = 3,
                            ProductCategory = "Teknoloji",
                            ProductFeatures = "İşletim Sistemi Tabanı Android, Ekran Modeli TFT,Ram Kapasitesi 4 GB,Ekran Boyutu 12,4 inç, Max Ekran Çözünürlüğü 2560 x 1600,Mobil BağlantıYok ",
                            ProductImgUrl = "https://productimages.hepsiburada.net/s/127/550/110000077439199.jpg/format:webp",
                            ProductName = "Samsung Galaxy Tab S7 FE ",
                            ProductPrice = 10719.0,
                            ProductStar = 9
                        },
                        new
                        {
                            ProductId = 4,
                            ProductCategory = "Teknoloji",
                            ProductFeatures = "Intel Core i3 1215U 8GB 256GB SSD Freedos 15.6",
                            ProductImgUrl = "https://productimages.hepsiburada.net/s/472/550/110000515070461.jpg/format:webp",
                            ProductName = "Asus Vivobook 15 ",
                            ProductPrice = 11999.0,
                            ProductStar = 8
                        },
                        new
                        {
                            ProductId = 5,
                            ProductCategory = "Teknoloji",
                            ProductFeatures = "Suya & Tere Dayanıklı Hayır ,Aktif Gürültü Önleme (ANC) Yok, Kullanım Tipi Kulaküstü ,Çift Telefon Desteği Var, Bluetooth Versiyon 5.3, ",
                            ProductImgUrl = "https://productimages.hepsiburada.net/s/406/222-222/110000434230608.jpg/format:webp",
                            ProductName = "Jbl Tune 520BT ",
                            ProductPrice = 1419.0,
                            ProductStar = 6
                        },
                        new
                        {
                            ProductId = 6,
                            ProductCategory = "Teknoloji",
                            ProductFeatures = "İşletim Sistemi Tabanı Android,Dahili Hafıza64 GB,Tablet İşlemci Qualcomm Snapdragon 439, Kamera Çift Kamera ,Mobil Bağlantı Yok ,Wi-Fi Var, Ekran Modeli IPS Ekran, Ram Kapasitesi 4GB , Ekran Boyutu 10,1 inç, Max Ekran Çözünürlüğü 1920 x 1200 ,",
                            ProductImgUrl = "https://productimages.hepsiburada.net/s/39/550/10641362518066.jpg/format:webp",
                            ProductName = "Lenovo Yoga Smart TAB TB-X705F ",
                            ProductPrice = 14999.0,
                            ProductStar = 7
                        },
                        new
                        {
                            ProductId = 7,
                            ProductCategory = "Teknoloji",
                            ProductFeatures = " Ergonomik tasarım kolay izleme ve yazma, boyun, omuz ve omurga ağrısını yaşamamanız için kullanışlıdır. Dizüstü bilgisayar ve tablet standı 7 kademeli ayarlanabilir yükseklik sağlar, gerçek ihtiyacınıza göre rahat çalışma açısı ve yüksekliğine ayarlayın ",
                            ProductImgUrl = "https://productimages.hepsiburada.net/s/456/550/110000492217118.jpg/format:webp",
                            ProductName = "Laptop Tablet Standı ",
                            ProductPrice = 330.0,
                            ProductStar = 9
                        },
                        new
                        {
                            ProductId = 8,
                            ProductCategory = "Teknoloji",
                            ProductFeatures = " Intel Core I7 11800H 32GB 1 TB SSD RTX3050TI Freedos 17.3 ",
                            ProductImgUrl = "https://productimages.hepsiburada.net/s/444/550/110000478561734.jpg/format:webp",
                            ProductName = "Monster Abra A7 V13.3.4",
                            ProductPrice = 29999.0,
                            ProductStar = 8
                        },
                        new
                        {
                            ProductId = 9,
                            ProductCategory = "Teknoloji",
                            ProductFeatures = "Asus TUF GAMING M3 Aura SYNC RGB 7000DPI  ",
                            ProductImgUrl = "https://productimages.hepsiburada.net/s/34/550/10447701934130.jpg/format:webp",
                            ProductName = "Oyuncu Mouse",
                            ProductPrice = 399.0,
                            ProductStar = 8
                        },
                        new
                        {
                            ProductId = 10,
                            ProductCategory = "Teknoloji",
                            ProductFeatures = "Aydınlatma Var , Mouse Formu Sağ, El Mouse Tipi Optik Mouse , Scroll-Tilt Yok,RGB Var, BağlantıKablolu ",
                            ProductImgUrl = "https://productimages.hepsiburada.net/s/44/550/10799730393138.jpg/format:webp",
                            ProductName = "Gaming Mouse",
                            ProductPrice = 3512.0,
                            ProductStar = 10
                        },
                        new
                        {
                            ProductId = 11,
                            ProductCategory = "Moda",
                            ProductFeatures = " Cinsiyet: Erkek ,Yaka Stili : Bisiklet Yaka  ,Desen:Düz Renk ,Kol Boyu:Truvakar Kol",
                            ProductImgUrl = "https://productimages.hepsiburada.net/s/440/550/110000474281671.jpg/format:webp",
                            ProductName = "U.S. Polo Assn. Erkek Antrasit Melanj Sweatshirt ",
                            ProductPrice = 849.0,
                            ProductStar = 8
                        },
                        new
                        {
                            ProductId = 12,
                            ProductCategory = "Moda",
                            ProductFeatures = "AC&Co / Altınyıldız Classics Rüzgar Geçirmez Taşınabilir Çantalı Sıcak Tutan Hafif Standart Fit Elyaf Dolgulu Şişme Erkek Mont ",
                            ProductImgUrl = "https://productimages.hepsiburada.net/s/483/550/110000528454412.jpg/format:webp",
                            ProductName = "Altınyıldız  Erkek Mont",
                            ProductPrice = 1999.0,
                            ProductStar = 9
                        },
                        new
                        {
                            ProductId = 13,
                            ProductCategory = "Moda",
                            ProductFeatures = "U.s. Polo Assn. Erkek Siyah Kanvas / Chino Pantolon 50275532-VR046 ",
                            ProductImgUrl = "https://productimages.hepsiburada.net/s/475/550/110000517846540.jpg/format:webp",
                            ProductName = "Erkek Siyah Kanvas / Chino Pantolo",
                            ProductPrice = 750.0,
                            ProductStar = 10
                        },
                        new
                        {
                            ProductId = 14,
                            ProductCategory = "Moda",
                            ProductFeatures = " Cinsiyet:Kadın Garanti Süresi (Ay) :12",
                            ProductImgUrl = "https://productimages.hepsiburada.net/s/452/550/110000487051994.jpg/format:webp",
                            ProductName = "U.S. Polo Assn. Kadın Lacivert Örme Elbise",
                            ProductPrice = 1800.0,
                            ProductStar = 7
                        },
                        new
                        {
                            ProductId = 15,
                            ProductCategory = "Moda",
                            ProductFeatures = " Cinsiyet:Kadın  ,Renk:Kırmızı ,Topuk Boyu:Yüksek ,Topuk Tipi:Stiletto",
                            ProductImgUrl = "https://productimages.hepsiburada.net/s/477/550/110000519939012.jpg/format:webp",
                            ProductName = "Desa Grace Kırmızı Kadın Stiletto Topuklu Ayakkabı",
                            ProductPrice = 1860.0,
                            ProductStar = 8
                        },
                        new
                        {
                            ProductId = 16,
                            ProductCategory = "Moda",
                            ProductFeatures = "Incı Wınston 3pr Siyah Erkek Klasik Ayakkabı 42 Numara ",
                            ProductImgUrl = "https://productimages.hepsiburada.net/s/438/550/110000471317764.jpg/format:webp",
                            ProductName = "Incı Wınston 3pr Siyah Erkek Klasik Ayakkabı",
                            ProductPrice = 1099.0,
                            ProductStar = 9
                        },
                        new
                        {
                            ProductId = 17,
                            ProductCategory = "Aksesuar",
                            ProductFeatures = "Paradise Work 3'lü Yılbaşı Biblo Seti Noelbaba Kardanadam Penguen ",
                            ProductImgUrl = "https://productimages.hepsiburada.net/s/482/550/110000527547160.jpg/format:webp",
                            ProductName = "Yılbaşı Biblo Seti",
                            ProductPrice = 178.0,
                            ProductStar = 9
                        },
                        new
                        {
                            ProductId = 18,
                            ProductCategory = "Ev",
                            ProductFeatures = "KİLİM MOBİLYA DOME KANEPE; MİNİMAL BİR ÇİZGİ TANIDIK BİR GÖRÜNÜM; OVAL FORMLAR; Kol kısmında kullanılan oval formlar Dome Kanepe’ye sevimli bir görüntü kazandırırken aynı zamanda yumuşak görünümlü kol yapısıyla kullanım rahatlığı da sağlar.; İ ",
                            ProductImgUrl = "https://productimages.hepsiburada.net/s/338/550/110000344102191.jpg/format:webp",
                            ProductName = "Kilim Mobilya Dome Üç Kişilik Kanepe",
                            ProductPrice = 5600.0,
                            ProductStar = 10
                        },
                        new
                        {
                            ProductId = 19,
                            ProductCategory = "Ciltbakım",
                            ProductFeatures = "Cildin yenilenme hızını artırır, leke ve izlerin daha çabuk iyileşmesini sağlar,Cildin daha sıkı ve pürüzsüz görünmesine yardımcı olur,Cilde nem, parlaklık ve elastikiyet katar,Yaşlanma belirtilerini hafifletir.",
                            ProductImgUrl = "https://productimages.hepsiburada.net/s/469/550/110000509693214.jpg/format:webp",
                            ProductName = "Serum Extra Yaşlanma Karşıtı ",
                            ProductPrice = 560.0,
                            ProductStar = 10
                        },
                        new
                        {
                            ProductId = 20,
                            ProductCategory = "Spor",
                            ProductFeatures = "Vites:24 Vites ,  Bisiklet Tipi:Dağ Bisikleti , Kadro Malzemesi:Alüminyum Ağırlık 14,6 kg ,  Fren Tipi:Hidrolik Disk Fren , Jant:29 inç, Kadro Boyu:18 inç - 46 cm ,Ön Amortisör :Kilitli Amortisör",
                            ProductImgUrl = "https://productimages.hepsiburada.net/s/55/550/11212783550514.jpg/format:webp",
                            ProductName = " Dağ Bisikleti ",
                            ProductPrice = 18000.0,
                            ProductStar = 10
                        },
                        new
                        {
                            ProductId = 21,
                            ProductCategory = "Beyaz Eşya",
                            ProductFeatures = "Genişlik (cm):60 , Yükseklik (cm):85 , Derinlik (cm): 55 , Kurutmalı: Hayır,Maksimum Devir Hızı:1200 Yıkama Kapasitesi:9 kg",
                            ProductImgUrl = "https://productimages.hepsiburada.net/s/76/550/110000017561925.jpg/format:webp",
                            ProductName = " Samsung  Çamaşır Makinesi ",
                            ProductPrice = 12000.0,
                            ProductStar = 8
                        },
                        new
                        {
                            ProductId = 23,
                            ProductCategory = "Aksesuar",
                            ProductFeatures = "Şans Bilekliği, Garanti Süresi: 1 Ay, Renk: Kırmızı, Kullanıcı Cinsiyeti: Unisex",
                            ProductImgUrl = "https://productimages.hepsiburada.net/s/86/550/110000028825785.jpg/format:webp",
                            ProductName = " Bileklik ",
                            ProductPrice = 50.0,
                            ProductStar = 8
                        },
                        new
                        {
                            ProductId = 24,
                            ProductCategory = "Aksesuar",
                            ProductFeatures = "Kolye, Garanti Süresi: 1 Ay, Renk: Kırmızı, Kullanıcı Cinsiyeti: Kadın, Kolye Ucu 925 Ayar Gümüş Kaplama üzeri Rose Kaplama",
                            ProductImgUrl = "https://productimages.hepsiburada.net/s/348/550/110000356146538.jpg/format:webp",
                            ProductName = " Kolye ",
                            ProductPrice = 200.0,
                            ProductStar = 9
                        },
                        new
                        {
                            ProductId = 25,
                            ProductCategory = "Aksesuar",
                            ProductFeatures = "Küpe, Garanti Süresi: 3 Ay, Renk: Siyah ve Gümüş, Kullanıcı Cinsiyeti: Kadın, ÜRÜN BOYUTU : HALKA : 8 MM ; FİGÜRLÜ KÜPE : 3 CM ; ZİRKON TAŞ : 4 MM",
                            ProductImgUrl = "https://productimages.hepsiburada.net/s/445/550/110000479147634.jpg/format:webp",
                            ProductName = " Küpe ",
                            ProductPrice = 200.0,
                            ProductStar = 9
                        },
                        new
                        {
                            ProductId = 26,
                            ProductCategory = "Ev",
                            ProductFeatures = "Üçlü Kanepe, Küçük kırlentlerde dolgu olarak silikon elyaf ve kırpıntı sünger karışımı kullanılmıştır.",
                            ProductImgUrl = "https://productimages.hepsiburada.net/s/171/550/110000134001181.jpg/format:webp",
                            ProductName = " Koltuk ",
                            ProductPrice = 10000.0,
                            ProductStar = 7
                        },
                        new
                        {
                            ProductId = 27,
                            ProductCategory = "Ev",
                            ProductFeatures = "Renk: Bej, İplik Cinsi (Micro Polyester), Hav Yüksekliği (8 mm), Halı Kalınlığı (12 mm), M2 Ağırlığı (2200 gr/m2), İlme Sayısı (400.000)",
                            ProductImgUrl = "https://productimages.hepsiburada.net/s/351/550/110000360212172.jpg/format:webp",
                            ProductName = " Halı ",
                            ProductPrice = 980.0,
                            ProductStar = 9
                        },
                        new
                        {
                            ProductId = 28,
                            ProductCategory = "Ev",
                            ProductFeatures = "Tül Perde, Taç Ekru Düz Tül 200 x 260 cm, Pilesiz düz dikimdir. Ekstrafordaki iplikler çekilerek istenildiği şekilde pile ayarı yapılabilir.",
                            ProductImgUrl = "https://productimages.hepsiburada.net/s/37/550/10544399286322.jpg/format:webp",
                            ProductName = " Perde ",
                            ProductPrice = 160.0,
                            ProductStar = 6
                        },
                        new
                        {
                            ProductId = 29,
                            ProductCategory = "Ciltbakım",
                            ProductFeatures = "C Vitamini, Parlaklaştırır, Gençleştirir, Lekeleri geçirir, Sabah akşam 1 kere temiz yüze uygulanır.",
                            ProductImgUrl = "https://productimages.hepsiburada.net/s/352/550/110000360596295.jpg/format:webp",
                            ProductName = " Serum ",
                            ProductPrice = 400.0,
                            ProductStar = 8
                        },
                        new
                        {
                            ProductId = 30,
                            ProductCategory = "Ciltbakım",
                            ProductFeatures = "Nemlendirici Bakım Maskesi, Haftada 2 kere temiz yüze ince bir katman halinde uygulanır. Cildi aydınlatır.",
                            ProductImgUrl = "https://productimages.hepsiburada.net/s/519/550/110000575513892.jpg/format:webp",
                            ProductName = " Maske ",
                            ProductPrice = 250.0,
                            ProductStar = 10
                        },
                        new
                        {
                            ProductId = 31,
                            ProductCategory = "Ciltbakım",
                            ProductFeatures = "Üçü bir arada yüz maskesi. Temizleme-Peeling-Maske Aynı anda",
                            ProductImgUrl = "https://www.hepsiburada.com/garnier-saf-temiz-peeling-3-u-1-arada-temizleme-maske-150-ml-p-SGGNRGARST3B?magaza=L%27Or%C3%A9al",
                            ProductName = " Maske ",
                            ProductPrice = 90.0,
                            ProductStar = 1
                        },
                        new
                        {
                            ProductId = 32,
                            ProductCategory = "Spor",
                            ProductFeatures = "Normal kalıp, Bağcıklı tasarım, Kumaş saya, Cloudfoam orta taban, Kumaş astar.",
                            ProductImgUrl = "https://productimages.hepsiburada.net/s/395/600-800/110000419759509.jpg/format:webp",
                            ProductName = " Ayakkabı ",
                            ProductPrice = 1450.0,
                            ProductStar = 8
                        },
                        new
                        {
                            ProductId = 33,
                            ProductCategory = "Spor",
                            ProductFeatures = "6 KG Dambıl Ağırlık Seti, 2 Adet 3 KG Dambıldan oluşur, Ürünlerimiz üretimden tarafınıza doğrudan sevk edilmektedir.",
                            ProductImgUrl = "https://productimages.hepsiburada.net/s/433/550/110000466185977.jpg/format:webp",
                            ProductName = " Ağırlık/Dambıl ",
                            ProductPrice = 200.0,
                            ProductStar = 9
                        },
                        new
                        {
                            ProductId = 34,
                            ProductCategory = "Spor",
                            ProductFeatures = "Motor Gücü: 4,25 hp: Eğim Var, Nabız Ölçme Sistemi: Var, Katlanabilme:Var",
                            ProductImgUrl = "https://productimages.hepsiburada.net/s/424/550/110000455324829.jpg/format:webp",
                            ProductName = " Yürüyüş Bandı ",
                            ProductPrice = 45000.0,
                            ProductStar = 10
                        },
                        new
                        {
                            ProductId = 35,
                            ProductCategory = "Beyaz Eşya",
                            ProductFeatures = "Yeni Philips Azur 8000 Serisi ile güçlü ütüleme. 260 g turbo buharla en inatçı kırışıklıkları bile tek seferde yok edebilirsiniz.",
                            ProductImgUrl = "https://productimages.hepsiburada.net/s/308/550/110000300858424.jpg/format:webp",
                            ProductName = " Ütü ",
                            ProductPrice = 0.0,
                            ProductStar = 5
                        },
                        new
                        {
                            ProductId = 36,
                            ProductCategory = "Beyaz Eşya",
                            ProductFeatures = "Ekran TipiLED Ekran, Özellik 1: Isı Pompalı, Özellik 2: 10 Kg Kurutma Kapasitesi, Özellik 3: Özel Karıştırıcı ve Çift Filtre",
                            ProductImgUrl = "https://productimages.hepsiburada.net/s/495/550/110000546072760.jpg/format:webp",
                            ProductName = " Kurutma Makinesi ",
                            ProductPrice = 22000.0,
                            ProductStar = 8
                        },
                        new
                        {
                            ProductId = 37,
                            ProductCategory = "Beyaz Eşya",
                            ProductFeatures = "Bosch SMS4IKI51T 5 Programlı Bulaşık Makinesi, 13L iç kapasite, A++ Enerji Tasarrufu",
                            ProductImgUrl = "https://productimages.hepsiburada.net/s/261/550/110000245316455.jpg/format:webp",
                            ProductName = " Bulaşık Makinesi ",
                            ProductPrice = 16700.0,
                            ProductStar = 7
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
